name: twilio_programmable_voice_example
description: Demonstrates how to use the twilio_programmable_voice plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_apns: ^1.4.1
  #  We might want to remove firebase_messagin in favor of flutter_apns
  # firebase_messaging: 7.0.3
  callkeep: ^0.2.3

  flutter_dotenv: ^2.1.0
  logger: ^0.9.4
  flutter_svg: ^0.19.1
  fluro: ^2.0.3
  flutter_bloc: ^6.1.3

  twilio_programmable_voice:
    # When depending on this package from a real application you should use:
    #   twilio_programmable_voice: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - .env
    - assets/icons/
    - assets/images/
  uses-material-design: true
